I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 11, in script call
    call intro
  File "game/script.rpy", line 29, in script
    if(playerGender == Male):
  File "game/script.rpy", line 29, in <module>
    if(playerGender == Male):
NameError: name 'Male' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 11, in script call
    call intro
  File "game/script.rpy", line 29, in script
    if(playerGender == Male):
  File "C:\Program Files (x86)\renpy-8.0.3-sdk\renpy\ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "C:\Program Files (x86)\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Program Files (x86)\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 29, in <module>
    if(playerGender == Male):
NameError: name 'Male' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
The Golden Gilfs 1.0
Sat Feb  4 14:06:28 2023
